# Generated by Django 5.2.3 on 2025-06-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiDigitalpathshala', '0004_category_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
